>数据预处理：1. 数据中性化； 2. 数据标准化

## 中位数去极值

In [25]:
import pandas as pd

In [26]:
data = pd.read_csv("gross_data/2012.csv", index_col = 0)

In [27]:
mons = list(set(list(data["time"])))

In [28]:
features = list(set(data.columns[2:-1]))

In [29]:
data.reset_index(inplace=True)

In [30]:
data.head()

,index,num_id,time,Capitalization,CirculatingCap,CirculatingMarketCap,MarketCap,PBRatio,PCFRatio,PSRatio,PeRatio,PeRatioLYR,TurnoverRatio,rf
0,0,1,2011-01,28023.884766,27641.720703,39.195999,39.737900,6.6313,307.808807,1.1069,-362.369110,1098.026245,0.7477,0.071027
1,1,2,2011-01,74236.500000,55504.933594,132.046204,176.608597,7.9575,-126.356201,14.3126,52.960999,59.916100,0.4747,-0.098876
2,2,3,2011-01,273765.000000,112129.125000,42.609100,104.030701,0.7682,-19.233200,0.1915,-9.451700,86.664803,0.9639,-0.005614
3,3,4,2011-01,49860.000000,31645.978516,19.652201,30.963100,2.3450,17.228600,3.3586,20.178200,18.619499,0.5904,-0.011135
4,4,5,2011-01,26780.000000,6700.000000,11.544100,46.141899,3.3848,-106.089500,3.5038,38.760700,54.792702,3.4828,0.075978

In [31]:
DM = pd.DataFrame(columns=["time"]+features)
DM

Empty DataFrame
Columns: [time, PBRatio, PeRatio, MarketCap, TurnoverRatio, Capitalization, CirculatingMarketCap, PCFRatio, PSRatio, PeRatioLYR, CirculatingCap]
Index: []

In [32]:
DM["time"] = mons

In [33]:
DM.head()

,time,PBRatio,PeRatio,MarketCap,TurnoverRatio,Capitalization,CirculatingMarketCap,PCFRatio,PSRatio,PeRatioLYR,CirculatingCap
0,2011-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
for i in range(len(mons)):
    for feature in features:
        DM[feature][i] = data[data["time"]==mons[i]][feature].median()

In [35]:
DM.head()

,time,PBRatio,PeRatio,MarketCap,TurnoverRatio,Capitalization,CirculatingMarketCap,PCFRatio,PSRatio,PeRatioLYR,CirculatingCap
0,2011-10,3.1926,30.9112,58.367001,0.9926,50700.0,39.0718,4.451,2.6987,37.420101,38187.367188
1,2011-08,3.536,35.364101,63.742199,0.7675,50232.210938,43.034801,8.3089,3.0793,41.016399,37868.019531
2,2011-11,3.0129,30.02225,55.789999,1.01795,50712.341797,37.141251,4.0784,2.59475,36.31815,38235.337891
3,2011-05,3.6274,36.447498,61.331501,0.758,48000.0,42.518799,7.1397,3.2259,39.472198,35979.539062
4,2011-01,4.0534,40.44095,63.802601,0.99115,45000.0,40.905651,10.54315,3.57755,51.5746,33714.138672

In [36]:
DM1 = pd.DataFrame(columns=["time"]+features)
DM1["time"] = mons

In [37]:
for i in range(len(mons)):
    for feature in features:
        DM1[feature][i] = (data[data["time"]==mons[i]][feature]-float(DM[DM["time"]==mons[i]][feature])).abs().median()

In [38]:
DM1.head()

,time,PBRatio,PeRatio,MarketCap,TurnoverRatio,Capitalization,CirculatingMarketCap,PCFRatio,PSRatio,PeRatioLYR,CirculatingCap
0,2011-10,1.1204,14.803801,25.624401,0.5972,24101.289062,19.6712,34.144199,1.6909,19.078598,23430.356445
1,2011-08,1.2544,17.002899,27.411499,0.4508,24162.210938,21.668501,36.974101,1.9238,20.026899,23737.621094
2,2011-11,1.10025,14.998049,24.625749,0.58225,24219.1875,18.716101,32.474501,1.63155,19.04115,23490.297852
3,2011-05,1.2991,16.665398,26.810101,0.4238,23235.5625,22.258499,38.3787,1.9654,17.617203,22187.576172
4,2011-01,1.4819,21.134449,27.639702,0.53025,22539.289062,20.836199,43.279501,2.1806,28.458201,20824.092285

In [39]:
Range = pd.DataFrame(columns=["bond"]+features)
Range

Empty DataFrame
Columns: [bond, PBRatio, PeRatio, MarketCap, TurnoverRatio, Capitalization, CirculatingMarketCap, PCFRatio, PSRatio, PeRatioLYR, CirculatingCap]
Index: []

In [40]:
Range["bond"] = ["lower_bond", "upper_bound"]

In [41]:

for feature in features:
    for i in range(data.shape[0]):
        lb = float(DM[DM["time"] == data["time"][i]][feature]) - 5 * float(DM1[DM1["time"] == data["time"][i]][feature])
        ub = float(DM[DM["time"] == data["time"][i]][feature]) + 5 * float(DM1[DM1["time"] == data["time"][i]][feature])
        if data[feature][i] < lb:
            data[feature][i] = lb
        if data[feature][i] > ub:
            data[feature][i] = ub

/tmp/ipykernel_22754/3737732328.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[feature][i] = ub
/tmp/ipykernel_22754/3737732328.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[feature][i] = lb

## 标准化

In [42]:
Mean = pd.DataFrame(columns=["time"]+features)
Mean["time"] = mons
st = pd.DataFrame(columns=["time"]+features)
st["time"] = mons

In [43]:
for i in range(len(mons)):
    for feature in features:
        Mean[feature][i] = data[data["time"]==mons[i]][feature].mean()

for i in range(len(mons)):
    for feature in features:
        st[feature][i] = data[data["time"]==mons[i]][feature].std()

In [44]:
for feature in features:
    for i in range(data.shape[0]):
        data[feature][i] = (data[feature][i] - Mean[Mean["time"]==data["time"][i]][feature])/st[st["time"]==data["time"][i]][feature]

/tmp/ipykernel_22754/3292597945.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[feature][i] = (data[feature][i] - Mean[Mean["time"]==data["time"][i]][feature])/st[st["time"]==data["time"][i]][feature]

In [45]:
data.to_csv("train_data/2012.csv")